GAME_KEYBIND_ATTRIBUTES = {
    "map": "KEYBIND_MAP",
    "daily_task": "KEYBIND_DAILY_TASK",
    "dress": "KEYBIND_DRESS",
    "take_photo": "KEYBIND_TAKE_PHOTO",
    "monthly_pass": "KEYBIND_MONTHLY_PASS",
    "item": "KEYBIND_ITEM",
    "event": "KEYBIND_EVENT",
    "interaction": "KEYBIND_INTERACTION",
    "bell": "KEYBIND_BELL",
    "ability_derivation_world_1": "KEYBIND_ABILITY_DERIVATION_WORLD_1",
    "ability_derivation_1": "KEYBIND_ABILITY_DERIVATION_1",
    "forward": "KEYBIND_FORWARD",
    "jump": "KEYBIND_JUMP",
    "falling": "KEYBIND_FALLING",
    "sprint": "KEYBIND_SPRINT",
    "tab": "KEYBIND_TAB",
    "back": "KEYBIND_BACK",
    "chat": "KEYBIND_CHAT",
    "fishing_reel_in": "KEYBIND_FISHING_REEL_IN",
    "ability_1": "KEYBIND_ABILITY_1",
    "ability_2": "KEYBIND_ABILITY_2",
    "ability_3": "KEYBIND_ABILITY_3",
    "ability_4": "KEYBIND_ABILITY_4",
    "ability_5": "KEYBIND_ABILITY_5",
    "ability_6": "KEYBIND_ABILITY_6",
    "ability_7": "KEYBIND_ABILITY_7",
    "ability_8": "KEYBIND_ABILITY_8",
}

GAME_KEYBIND_IDS = frozenset(GAME_KEYBIND_ATTRIBUTES)
